name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 21
          - 22
          - 23
          - 24
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci
      - run: npm test
